<a href="https://colab.research.google.com/github/MashMaleLLO/Project_APS_CE_DEV/blob/master/nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U pandasql

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandasql in /usr/local/lib/python3.7/dist-packages (0.7.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.4.41)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->pandasql) (1.15.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (1.1.3)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (4.12.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (3.8.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (4.1.1)

In [ ]:
pip install --user -U nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (3.7)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from nltk) (4.64.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.7/dist-packages (from nltk) (2022.6.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from nltk) (1.1.0)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from nltk) (7.1.2)

In [ ]:
import pandas as pd
import os
import gensim
import spacy
import en_core_web_sm
import nltk
import math
nltk.download('stopwords')
from nltk.corpus import stopwords
STOPWORDS = set(stopwords.words('english'))

nlp = en_core_web_sm.load()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
df = pd.read_csv('2560+2564.csv',dtype={1:'string'},encoding='TIS-620')
df = df.drop_duplicates('subject_id', keep='first')
df = df.reset_index()
df

,index,subject_id,subject_name_thai,subject_name_eng,abstract,subject_key,subject_type,year,subject_class
0,0,1006030,แคลคูลัส 1,CALCULUS 1,"Function, Limit, Continuity and their applicat...",NaN,คณิตศาสตร์,2560,NaN
1,1,1006031,แคลคูลัส 2,CALCULUS 2,Functions of several variables and theirs appl...,NaN,คณิตศาสตร์,2560,NaN
2,2,1006032,สมการอนุพันธ์และพีชคณิตเชิงเส้นพื้นฐาน,ELEMENTARY DIFFERENTIAL EQUATIONS AND LINEAR A...,Systems of linear equations and solutions. vec...,NaN,คณิตศาสตร์,2560,NaN
3,3,1006004,การฝึกงานอุตสาหกรรม,INDUSTRIAL TRAINING,"During their four-year selected studies, stude...",NaN,เลือกภาค,2560,NaN
4,4,1006028,เตรียมความพร้อมสําหรับวิศวกร,PRE-ENGINEER ACTIVITIES,Participates in activities organized by the Fa...,NaN,เลือกภาค,2560,NaN
...,...,...,...,...,...,...,...,...,...
110,145,1076635,เครือข่ายสวิตซ์ไอพี,IP SWITCHED NETWORKS,The main objective of this course is to provid...,"โครงสร้างพื้นฐานของระบบ,เน็ตเวิร์ค",เลือกภาค,2564,NaN
111,147,1076592,ผู้ประกอบการกับวิศวกร,ENTREPRENEURSHIP AND THE ENGINEER,"Discusses basic concepts of marketing, busines...",วิชาบูรณาการ,เลือกภาค,2564,NaN
112,148,1076422,การประกอบการและการจัดการด้านเทคโนโลยีสารสนเทศ,IT ENTREPRENEURSHIP AND MANAGEMENT,This course covers the basic of IT entrepreneu...,วิชาบูรณาการ,เลือกภาค,2564,NaN
113,149,1076423,การวางแผนเชิงกลยุทธ์โดยใช้บอร์ดและการ์ดเกม,STRATEGIC PLANNING USING BOARD AND CARD GAME,"This course covers the strategic planning, stu...",วิชาบูรณาการ,เลือกภาค,2564,NaN
114,150,1076577,การจัดการโครงการเทคโนโลยีสารสนเทศ,IT PROJECT MANAGEMENT,Meaning of Project; Importance of information ...,วิชาบูรณาการ,เลือกภาค,2564,NaN

In [ ]:
for sentence in df['abstract']:
  newsentence = sentence
  listnewsentence = []
  for i in newsentence.split():
    i = i.replace(';',"")
    i = i.replace(',',"")
    listnewsentence.append(i)
  newsentence = set(listnewsentence) - set(STOPWORDS)   
  newsentence = " ".join(list(newsentence))
  df = df.replace({'abstract': sentence}, {'abstract': newsentence}, regex=True)
df

,index,subject_id,subject_name_thai,subject_name_eng,abstract,subject_key,subject_type,year,subject_class
0,0,1006030,แคลคูลัส 1,CALCULUS 1,Introduction Application Numerical Improper Co...,NaN,คณิตศาสตร์,2560,NaN
1,1,1006031,แคลคูลัส 2,CALCULUS 2,Lines Functions theorem Introduction variables...,NaN,คณิตศาสตร์,2560,NaN
2,2,1006032,สมการอนุพันธ์และพีชคณิตเชิงเส้นพื้นฐาน,ELEMENTARY DIFFERENTIAL EQUATIONS AND LINEAR A...,Linear Introduction Application etc. transform...,NaN,คณิตศาสตร์,2560,NaN
3,3,1006004,การฝึกงานอุตสาหกรรม,INDUSTRIAL TRAINING,conditions activities complete presented pract...,NaN,เลือกภาค,2560,NaN
4,4,1006028,เตรียมความพร้อมสําหรับวิศวกร,PRE-ENGINEER ACTIVITIES,organized activities project Faculty students ...,NaN,เลือกภาค,2560,NaN
...,...,...,...,...,...,...,...,...,...
110,145,1076635,เครือข่ายสวิตซ์ไอพี,IP SWITCHED NETWORKS,LAN cover security The technologies. course vi...,"โครงสร้างพื้นฐานของระบบ,เน็ตเวิร์ค",เลือกภาค,2564,NaN
111,147,1076592,ผู้ประกอบการกับวิศวกร,ENTREPRENEURSHIP AND THE ENGINEER,analysis plans new appreciate management entre...,วิชาบูรณาการ,เลือกภาค,2564,NaN
112,148,1076422,การประกอบการและการจัดการด้านเทคโนโลยีสารสนเทศ,IT ENTREPRENEURSHIP AND MANAGEMENT,Effective covers customer entrepreneurship man...,วิชาบูรณาการ,เลือกภาค,2564,NaN
113,149,1076423,การวางแผนเชิงกลยุทธ์โดยใช้บอร์ดและการ์ดเกม,STRATEGIC PLANNING USING BOARD AND CARD GAME,analysis covers board game strategic Strategic...,วิชาบูรณาการ,เลือกภาค,2564,NaN
114,150,1076577,การจัดการโครงการเทคโนโลยีสารสนเทศ,IT PROJECT MANAGEMENT,Importance technology scope management Project...,วิชาบูรณาการ,เลือกภาค,2564,NaN

In [ ]:
thisdict = {}
all_docs = [nlp(row) for row in df['abstract']]
num = 0
for i in range(len(all_docs)):
  check = 0
  sims = []
  if list(thisdict.keys()) == []:
    thisdict[num] = [df.loc[df.index == i, 'subject_id'].iloc[0]]
    num += 1
  else:
    for x in thisdict:
      temp = df.loc[df['subject_id'] == thisdict[x][0], 'abstract'].iloc[0]
      sim = all_docs[i].similarity(nlp(temp))
      sims.append(sim)
    maxsim = max(sims)
    for x in thisdict:
      temp = df.loc[df['subject_id'] == thisdict[x][0], 'abstract'].iloc[0]
      sim = all_docs[i].similarity(nlp(temp))
      if sim >= 0.90 and sim == maxsim:
        thisdict[x].append(df.loc[df.index == i, 'subject_id'].iloc[0])
        check = 1
        break
    if check != 1:
      thisdict[num] = [df.loc[df.index == i, 'subject_id'].iloc[0]]
      num += 1
print(thisdict)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.

{0: [1006030, 1006032, 1076028, 1076591, 1076574, 1076585, 1076140, 1076042, 1076043, 1076044], 1: [1006031, 1076141], 2: [1006004], 3: [1006028], 4: [1076003, 1076107], 5: [1076253], 6: [1076002, 1076004, 1076103, 1076104, 1076105, 1076106, 1076592], 7: [1076001, 1076101], 8: [1076005, 1076109, 1076110], 9: [1076006, 1076112, 1076113], 10: [1076007, 1076008, 1076263, 1076014, 1076023, 1076411, 1076568, 1076566, 1076597, 1076628, 1076584, 1076016, 1076034, 1076035, 1076423, 1076577], 11: [1076009, 1076114, 1076115], 12: [1076010, 1076011, 1076632, 1076032, 1076116, 1076117], 13: [1076012, 1076021, 1076022, 1076513, 1076567, 1076050, 1076051, 1076414], 14: [1076013, 1076582, 1076121], 15: [1076015], 16: [1076024, 1076559], 17: [1076025, 1076119, 1076120], 18: [1076026, 1076036, 1076037], 19: [1076027, 1076040, 1076041], 20: [1076029, 1076118], 21: [1076311, 1076312], 22: [1076418], 23: [1076419, 1076053], 24: [1076420], 25: [1076421], 26: [1076561], 27: [1076564], 28: [1076589], 29: [1076595, 1076599, 1076636], 30: [1076596], 31: [1076634], 32: [1076598], 33: [1076583], 34: [1076532], 35: [1076627], 36: [1076629], 37: [1076614], 38: [1076630], 39: [1076631], 40: [1076633], 41: [1076108], 42: [1076052], 43: [1006029], 44: [1006005], 45: [1076558], 46: [1076560], 47: [1076533], 48: [1076635], 49: [1076422]}